spring:
  application:
    name: CleanArchitectureApp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.6:3306/clean_architecture
    username: deploy
    password: Hello@123456

mybatis:
  config-location: classpath:mybatis-config.xml
#
#app:
#  name: spring boot application
#  api:
#    title: Spring Boot APIs
#    version: 1.0.0
#    description: Spring Boot APIs description
#    base-package: clean.architecture.web
#    contact-name: James Zhan
#    contact-email: zhiqiangzhan@gmail.com
#    swagger:
#      enable: true